# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6981a00d753db46bb4ec24e37116f599d24da8893ed70d31437945bd21f54b89145c44fcce2e56a4ce1a4d3e8994907189a119ddc8c7bf2ece8d3029c48604b5

test:
  secret_key_base: 6dab358f2ad5f3bbb240d9e5a743226d6b09031b96b343465d2313c47bb219226bf8d8f68c5304acfb70ae036c12013c7247fd16c67cfe693ba2463c2400f92e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
